### PR TITLE
docs: Updates CHANGELOG.md

### LINKED ISSUE #57: Broken link between CHANGELOG and README
This line in [CHANGELOG](https://github.com/okta/okta-react/blob/master/CHANGELOG.md)
```md
- [#8](https://github.com/okta/okta-react/pull/8) See [MIGRATING](README#migrating-from-3x-to-4x) for detailed information.
```

needs to be changed to

```md
- [#8](https://github.com/okta/okta-react/pull/8) See [MIGRATING](README.md#migrating-from-3x-to-4x) for detailed information.
```

### PR DESCRIPTION
**Pull request by brockthebear**
Fixes a broken link between CHANGELOG.md and README.md.

Fixes #57

### CODE REVIEW

**Comment by swiftone** [comment]
/me pokes at the failing CI test curiously

**Comment by brockthebear** [comment]
@swiftone - Ha! I'm just as surprised as you are. I'll take a closer look as soon as I get the chance tomorrow.

**Comment by swiftone** [comment]
We've been doing some test shuffles so our Travis config may be confused, I'll keep at it.

**Comment by shuowu** [comment]
@brockthebear Thanks for the contribution! I'll get the PR converted and merged.

Internal Ref: OKTA-365162

**Comment by shuowu** [comment]
Moved to #80

**Pull request closed without merging**
