### PR TITLE
Add loadingComponent prop to LoginCallback component

### PR DESCRIPTION
**Pull request by swiftone**
Quoting original PR( #58 ) from @ericlifs:

### Actual result
The LoginCallback components shows an empty white page while the authentication is being performed

### What this PR does
This PR gives the developer the possibility to set any custom component that he/she wants to show while Okta's authentication is being done instead of just returning a null value

### CODE REVIEW

**Comment by shuowu** [comment]
It would be great to cover the loading scenario in jest and e2e test.

**Review by aarongranick-okta — CHANGES_REQUESTED** [review]
code looks good.
please add tests

**Comment by tomspeak** [comment]
Is there an estimate of when this will land? I currently manually handle this functionality.

**Comment by shuowu** [comment]
Internal Ref: OKTA-404404

**Review by denysoblohin-okta — APPROVED** [review]

**Review by shuowu — APPROVED** [review]

**Pull request closed without merging**
