### PR TITLE
restoreOriginalUri warning & routing samples

### PR DESCRIPTION
**Pull request by jaredperreault-okta**
Fixes 'Two custom restoreOriginalUri callbacks are detected' warning
Updates routing samples (v6) to fix unnecessary calls to /authorize

### CODE REVIEW

**Review by shuowu-okta — APPROVED** [review]

**Comment by code-bode** [comment]
I clone the latest code and try to run locally **React-Router-DOM-v6** project and still seeing this error. Am i missing anything to fix this issue.

image

**Comment by jaredperreault-okta** [comment]
@code-bode can you provide more details? I just ran the `cd samples/routing/react-router-dom-v6 && yarn dev` and I got no error.

Did you run `yarn` before trying the sample?

**Comment by code-bode** [comment]
@jaredperreault-okta  Yes, I ran yarn. This error appearing when I started clicking **protected** link multiple time on home page.

**Comment by jaredperreault-okta** [comment]
I assume this is when your unauthenticated? Are you redirected to your Okta Org after clicking **protected**?

I still cannot reproduce this

**Comment by jaredperreault-okta** [comment]
I just did a completely fresh test. 

1. Cloned the repo into a separate directory
2. ran `yarn`
3. setup `testenv` file
4. `cd samples/routing/react-router-dom-6`
5. `yarn start`

Tested in Chrome 103 and FF 102. No errors

**Comment by code-bode** [comment]
You are correct. I think issue is on my side. I have manually change below two packages  `"@okta/okta-auth-js": "6.6.1"` , `"@okta/okta-react": "^6.4.3"` with different version thinking it's latest version. Even updating **react-router-dom** to version `6.3.0` app is working fine. 

Sorry for all the confusion.

**Comment by jaredperreault-okta** [comment]
@code-bode No problem at all! We can only fix the bugs we know about. Thank you for the report

**Comment by code-bode** [comment]
I know using `*` packages.json means use the latest version for that package, but I updated these two packages from `*` to their latest version `"@okta/okta-auth-js": "6.7.2"` , `"@okta/okta-react": "6.5.0"` I am seeing that error. Do you think am i still doing something wrong?

**Comment by jaredperreault-okta** [comment]
Ok, I see what is happening.

So we use `*` in the package.json because the `samples` are all `yarn workspaces`. (`*` will install the latest, if there is no other "version" of the module installed, from another workspace or otherwise).  Therefore `@okta/okta-react: "*"` will pull from the locally built package, the top-level workspace (this is built as a result of running `yarn`). `master` is "at" `6.6.0` and includes this [PR](https://github.com/okta/okta-react/commit/5afc5efb4918ba09a7d3aa0ea4776b239b76533a) which specifically fixes this warning.

So when you specify `@okta/okta-react: "6.5.0"`, you'll actually pull the module from `npm` and `6.5.0` does not include the `restoreOriginalUri` fix.

I'll work on getting `6.6.0` released

**Comment by code-bode** [comment]
I will be waiting for version `6.6.0`. Thanks.

**Comment by pzi** [comment]
Great, thanks for this. Looking forward to 6.6

**Comment by pzi** [comment]
Works 👍🏼

**Pull request closed without merging**
